context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "GameAudio"
            capture.props = {
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                audio.position = [ FL FR ]
                node.target = "alsa_output.default"
            }
        }
    }
      }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "VoiceChat"
            capture.props = {
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                audio.position = [ FL FR ]
                node.target = "alsa_output.default"
            }
        }
    }
context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Audio"
            capture.props = {
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                audio.position = [ FL FR ]
                node.target = "alsa_output.default"
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "VoiceChat"
            capture.props = {
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                audio.position = [ FL FR ]
                node.target = "alsa_output.default"
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Capture Card"
            capture.props = {
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                audio.position = [ FL FR ]
                node.target = "alsa_output.default"
            }
        }
    }
  }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Capture Card"
            capture.props = {
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                audio.position = [ FL FR ]
                node.target = "alsa_output.default"
            }
        }
    }
  }
]
